hkabtrak/absences/views.py
import threading
from datetime import datetime, date, timedelta

from flask import Blueprint, render_template, request, redirect, url_for, flash, get_flashed_messages, current_app, \
    jsonify
from flask_login import login_required, current_user
from wtforms.validators import DataRequired

from hkabtrak import db, mail, bcc_address
from hkabtrak.absence_form import AbsenceForm
from hkabtrak.models import Absence, Class, load_user, User, Semester, load_course
from hkabtrak.util import admin_required, send_email

absences_bp = Blueprint('absences', __name__, template_folder='templates')

valid_types = ['欠席', '遅刻', '早退', '中抜け']


@absences_bp.route('/record_absence', methods=['GET', 'POST'])
def record_absence():
    form = AbsenceForm()

    default_course_choice = [('', '学年を選択してください')]
    form.class_id.choices = default_course_choice + [
        (cls.id, cls.name, {'data-instructions': cls.instructions or 'None'}) for cls in Class.query.all()
    ]

    if request.method == 'POST':
        reason = form.reason.data
        # Add conditional validators
        if reason == '遅刻':
            form.start_time.validators.append(DataRequired(message="Expected time is required for 'Late'."))
        if reason == '早退':
            form.end_time.validators.append(DataRequired(message="Leaving time is required for 'Leaving Early'."))
        if reason == '中抜け':
            form.start_time.validators.append(DataRequired(message="Leaving time is required for 'Absent for a Time'."))
            form.end_time.validators.append(DataRequired(message="Return time is required for 'Absent for a Time'."))

        # Then validate the form
        if not form.validate():
            print("Form validation errors:", form.errors)  # Debugging
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f"Error in {getattr(form, field).label.text}: {error}", 'danger')
            return render_template('new_absence.html', form=form)

    if current_app.config.get('RECAPTCHA_DISABLED', True):
        captcha_response = 'testing'
    else:
        captcha_response = request.form['g-recaptcha-response']

    if len(captcha_response) > 0:
        parent_email = form.parent_email.data
        class_id = form.class_id.data
        grade_name = load_course(class_id).name
        student_name = form.student_name.data
        absence_type = form.absence_type.data
        reason = form.reason.data
        start_time = form.start_time.data
        end_time = form.end_time.data
        comment = form.comment.data
        date = form.date.data

        if reason == 'その他':
            reason = 'その他' + ': ' + form.other_reason.data

        absence = Absence(
            student_name=student_name,
            reason=reason,
            class_id=class_id,
            date=date,
            start_time=start_time,
            end_time=end_time,
            parent_email=parent_email,
            absence_type=absence_type,
            comment=comment
        )
        db.session.add(absence)
        db.session.commit()

        cls = Class.query.get(class_id)
        if cls:
            staff_emails = [user.email for user in cls.staff]
            send_absence_notification(parent_email, staff_emails, student_name, grade_name, absence_type, reason, date,
                                      start_time, end_time,
                                      comment)

        get_flashed_messages(with_categories=True)
        return redirect(url_for('root.thank_you'))
    else:
        get_flashed_messages(with_categories=True)

    today = datetime.today().strftime('%Y-%m-%d')
    return render_template('new_absence.html', form=form, today=today)


@absences_bp.route('/thank_you')
def thank_you():
    return render_template('absence_submited.html')


@absences_bp.route('/list', methods=['GET', 'POST'])
@login_required
def list():
    user = load_user(current_user.get_id())
    if not user:
        return redirect(url_for('login'))

    if user.user_type == 'A':
        classes = Class.query.all()
    else:
        classes = user.classes
    all_absences = []
    date_filter = request.args.get('filterDate')  # Get date filter from query parameters

    try:
        # Convert the date from string to datetime.date object if provided
        selected_date = datetime.strptime(date_filter, '%Y-%m-%d').date() if date_filter else None
    except TypeError:
        selected_date = None

    for class_obj in classes:
        if selected_date:
            # Filter absences by class and selected date if a date is provided
            absences = Absence.query.filter_by(class_id=class_obj.id, date=selected_date).all()
        else:
            # Get all absences if no date is provided
            absences = Absence.query.filter_by(class_id=class_obj.id).all()
        all_absences.extend(absences)

    all_absences_sorted = sorted(all_absences, key=lambda x: x.date, reverse=True)
    this_saturday = date.today() + timedelta((5 - date.today().weekday()) % 7)

    return render_template('list.html', absences=all_absences_sorted, classes=classes, this_saturday=this_saturday,
                           selected_date=selected_date)


@absences_bp.route('/api/delete_absence/<int:absence_id>', methods=['DELETE'])
@login_required
@admin_required
def delete_absence(absence_id):
    # Get the absence record
    absence = Absence.query.get(absence_id)

    if absence:
        # Delete the record
        db.session.delete(absence)
        db.session.commit()
        return jsonify({"success": True}), 200
    else:
        return jsonify({"error": "Absence not found"}), 404


@absences_bp.route('/students')
@login_required
def students():
    today = date.today()
    user = load_user(current_user.get_id())

    # Fetch all classes where the teacher is involved
    if user.user_type == 'A':
        classes = Class.query.all()
    else:
        classes = Class.query.join(Class.staff).filter(User.id == current_user.id).all()

    semesters = Semester.query.order_by(Semester.start_date.asc()).all()  # Order by start date descending
    selected_semester_id = request.args.get('semester_id', type=int)

    selected_semester = None

    if selected_semester_id:
        selected_semester = Semester.query.get(selected_semester_id)
    else:
        # Default to the current semester
        for semester in semesters:
            if semester.start_date <= today <= semester.end_date:
                selected_semester = semester
                break
        # If no current semester, default to the most recent one
        if not selected_semester and semesters:
            selected_semester = semesters[0]

    class_absences_summary = {}
    if selected_semester:
        for cls in classes:
            student_absences = {}
            for absence in cls.absences:
                if selected_semester.start_date <= absence.date <= selected_semester.end_date:
                    if absence.student_name not in student_absences:
                        student_absences[absence.student_name] = {'days': 0, 'hours': 0}

                    if absence.absence_type == '欠席':
                        if absence.student_name in student_absences:
                            student_absences[absence.student_name]['days'] += 1
                    else:
                        duration = calculate_absence_duration(cls, absence)
                        if absence.student_name in student_absences:
                            student_absences[absence.student_name]['hours'] += duration

            if student_absences:
                class_absences_summary[(cls.name, cls.id)] = student_absences

    return render_template('by_student.html', class_absences=class_absences_summary, semesters=semesters,
                           selected_semester=selected_semester)


@absences_bp.route('/student/<int:grade>/<student_name>/', methods=['GET', 'POST'])
def student_absences(grade, student_name):
    semesters = Semester.query.order_by(Semester.start_date.asc()).all()
    selected_semester_id = request.args.get('semester_id', type=int)

    if selected_semester_id is None or selected_semester_id == -1:  # -1 for 'All Time'
        absences = Absence.query.join(Absence.course).filter(Absence.student_name == student_name,
                                                             Class.id == grade).all()
        selected_semester = None
    else:
        selected_semester = Semester.query.get(selected_semester_id)
        absences = Absence.query.join(Absence.course).filter(
            Absence.student_name == student_name,
            Absence.date.between(selected_semester.start_date, selected_semester.end_date),
            Class.id == grade
        ).all()

    days_missed = 0
    for absence in absences:
        if absence.absence_type != '欠席':
            duration = calculate_absence_duration(absence.course, absence)
            setattr(absence, 'duration', duration)
        else:
            setattr(absence, 'duration', 0)
            days_missed += 1

    return render_template('single_student.html', absences=absences, semesters=semesters,
                           selected_semester=selected_semester, student_name=student_name, grade=grade,
                           days_missed=days_missed)


def calculate_absence_duration(cls, absence):
    # Start and end times of the class and lunch
    class_start = datetime.combine(absence.date, cls.day_start)
    class_end = datetime.combine(absence.date, cls.day_end)
    lunch_start = datetime.combine(absence.date, cls.lunch_start)
    lunch_end = datetime.combine(absence.date, cls.lunch_end)

    match absence.absence_type:
        case '欠席':  # Absent
            absence_start = class_start
            absence_end = class_end
        case '遅刻':  # Late
            absence_start = class_start
            absence_end = datetime.combine(absence.date, absence.start_time)
        case '早退':  # Leaving Early

hkabtrak/absences/templates/by_student.html
{% extends "chrome.html" %}

{% block content %}
<div class="container mt-3">
    <h1>生徒別欠課概要</h1>
    <form action="{{ url_for('absences.students') }}" method="get">
        <div class="form-group">
            <label for="semesterSelect">学期を選択する:</label>
            <select name="semester_id" id="semesterSelect" class="form-control" onchange="this.form.submit()">
                {% for semester in semesters %}
                <option value="{{ semester.id }}" {% if selected_semester and selected_semester.id == semester.id %}selected{% endif %}>
                    {{ semester.name }} ({{ semester.start_date.strftime('%Y-%m-%d') }} - {{ semester.end_date.strftime('%Y-%m-%d') }})
                </option>
                {% endfor %}
            </select>
        </div>
    </form>

    {% for (class_name, class_id), students in class_absences.items() %}
    <h2>{{ class_name }}</h2>
    <table class="table">
        <thead>
            <tr>
                <th>生徒氏名</th>
                <th>欠席日数</th>
                <th>欠課時間</th>
            </tr>
        </thead>
        <tbody>
            {% for student_name, absence_info in students.items() %}
            <tr>
                <td><a href="{{  url_for('absences.student_absences', grade=class_id, student_name=student_name) }}">{{ student_name }}</a></td>
                <td>{{ "%.0f" | format(absence_info['days']) }}</td>
                <td class="duration" data-hours="{{ absence_info['hours'] }}"></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endfor %}
</div>

<script>
function formatDuration(hours) {
    const totalMinutes = Math.floor(hours * 60);
    const hoursPart = Math.floor(totalMinutes / 60);
    const minutesPart = totalMinutes % 60;
    return `${hoursPart}h ${minutesPart}min`;
}

document.querySelectorAll('.duration').forEach(element => {
    const hours = parseFloat(element.dataset.hours);
    element.textContent = formatDuration(hours);
});
</script>


{% endblock %}

hkabtrak/absences/templates/list.html
{% extends "chrome.html" %}

{% block content %}
<script>
    var thisWeekOnly = true;
    var currentClass = 'all';
</script>
<div class="container mt-3">
    <div class="d-flex justify-content-between align-items-center mb-3">
        {%  if selected_date %}
        <h1 id="pageTitle">生徒欠課概要 {{ selected_date }}</h1>
        {% else %}
        <h1 id="pageTitle">生徒欠課概要閲覧ページ</h1>
        {% endif %}
        <div>
            <a href="{{ url_for('absences.students') }}" class="btn btn-primary">生徒別欠課概要</a>
            <a href="{{ url_for('staff.staff_logout') }}" class="btn btn-danger">ログアウト</a>
        </div>
    </div>    <div class="d-flex justify-content-between align-items-end">
        <!-- Class Buttons for Filtering -->
            <div class="btn-group mb-3" role="group" aria-label="Class Filters">
                <button type="button" class="btn btn-secondary" onclick="filterAbsences('all', '全学年')">全学年</button>
                {% for class in classes %}
                    <button type="button" class="btn btn-secondary"
                            onclick="filterAbsences('{{ class.id }}', '欠課概要 {{ class.name }}')">{{ class.name }}</button>
                {% endfor %}
                {%  if not selected_date %}
                <button type="button" class="btn btn-info" id="modeButton" onclick="showNonCurrentAbsences()">すべての欠課連絡を見る</button>
                {% endif %}
            </div>

        <!-- Date Selector -->
        <div class="form-row align-items-center mb-3">
            <div class="col-auto">
                <label for="filterDate" class="form-label">日付指定:</label>
            </div>
            <div class="col-auto">
                <input type="date" class="form-control" id="filterDate" name="filterDate" value="{{ selected_date }}">
            </div>
            <div class="col-auto">
                <button type="button" class="btn btn-primary" onclick="filterByDate()">送信</button>
            </div>
        </div>
    </div>


{#    <div class="container mt-3 mb-3">#}
    <h2 id="currentClassHeading">生徒欠課概要</h2> <!-- Dynamic heading -->
{#    </div>#}

    <!-- Absences Table -->
    <div class="table-responsive">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th>生徒氏名</th>
                <th>欠課種類</th>
                <th>理由</th>
                <th>日付</th>
                <th>開始時間</th>
                <th>終了時間</th>
                <th>Email</th>
                <th>宿題受け渡し方法</th>
                <th>学年</th>
                {% if current_user.user_type == 'A' %}
                    <th>削除</th>
                {% endif %}

            </tr>
            </thead>
            <tbody>
            {% set previous_date = None %}
            {% for absence in absences %}
                {% if previous_date and previous_date > this_saturday and absence.date <= this_saturday %}
                    <tr>
                        <td colspan="8" class="bg-dark"></td>
                    </tr> <!-- Draw line for week boundary -->
                {% endif %}

                {%  if not selected_date %}
                <tr {% if absence.date > this_saturday %}style="color: lightgrey; display: none;"{% elif absence.date < this_saturday %}
                    style="color: gray; display: none;"{% endif %} class="absence-entry" data-absence-id="{{ absence.id }}"
                    data-class-id="{{ absence.class_id }}"
                    data-current="{% if absence.date != this_saturday %}false{% else %}true{% endif %}">
                {% else %}
                    <tr class="absence-entry" data-class-id="{{ absence.class_id }}"
                    data-current="true">
                {% endif %}
                    <td>{{ absence.student_name }}</td>
                    <td>{{ absence.absence_type }}</td>
                    <td>{{ absence.reason }}</td>
                    <td>{{ absence.date.strftime('%Y-%m-%d') }}</td>
                    <td>{{ absence.start_time.strftime('%H:%M') if absence.start_time else ' ' }}</td>
                    <td>{{ absence.end_time.strftime('%H:%M') if absence.end_time else ' ' }}</td>
                    <td>{{ absence.parent_email }}</td>
                    <td style="white-space: pre-wrap;"> {{ absence.comment }}</td>
                    <td>{{ absence.course.name }}</td>
                    {% if current_user.user_type == 'A' %}
                        <td>
                            <button class="btn btn-danger btn-sm" onclick="confirmDeleteAbsence({{ absence.id }})">
                            削除
                            </button>
                        </td>
                    {% endif %}
                </tr>
                {% set previous_date = absence.date %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
    function filterAbsences(classId, className) {
        const rows = document.querySelectorAll('.absence-entry');
        currentClass = classId;
        rows.forEach(row => {
            if ((classId === 'all' || parseInt(row.dataset.classId) === parseInt(currentClass))) {
                if (row.dataset.current === 'true') {
                    row.style.display = '';
                } else if (thisWeekOnly === false) {
                    row.style.display = '';
                }
            } else {
                row.style.display = 'none';
            }
        });
        document.getElementById("currentClassHeading").textContent = className; // Update heading based on selected class

    }

    function showNonCurrentAbsences() {
        const rows = document.querySelectorAll('.absence-entry');
        rows.forEach(row => {
            if (row.dataset.current === 'false' && (currentClass==='all' || row.dataset.classId === currentClass)) {
                row.style.display = '';
            }
        });
        const modeButton = document.getElementById("modeButton")
        thisWeekOnly=false;
        modeButton.innerText="今週の欠課連絡を見る"
        modeButton.onclick= hideNonCurrentAbsences;
    }

    function hideNonCurrentAbsences() {
        const rows = document.querySelectorAll('.absence-entry');
        rows.forEach(row => {
            if (row.dataset.current === 'false') {
                row.style.display = 'none';
            }
        });
        const modeButton = document.getElementById("modeButton")
        thisWeekOnly = true;
        modeButton.innerText="すべての欠課連絡を見る"
        modeButton.onclick= showNonCurrentAbsences;
    }

    function filterByDate() {
        const dateValue = document.getElementById('filterDate').value;
        if (dateValue) {
            const currentURL = window.location.href.split('?')[0];  // Remove any existing query parameters
            window.location.href = `${currentURL}?filterDate=${dateValue}`;  // Redirect to the same route with the date as a query parameter
        } else {
            alert('Please select a date.');
        }
    }
        function confirmDeleteAbsence(absenceId) {
        // Show a confirmation dialog
        if (confirm("この欠席記録を削除してもよろしいですか？")) {
            // If confirmed, send an AJAX request to delete the absence
            deleteAbsence(absenceId);
        }
    }

    function deleteAbsence(absenceId) {
        fetch(`/absences/api/delete_absence/${absenceId}`, {
            method: 'DELETE',
            headers: {
                'X-CSRFToken': "{{ csrf_token() }}"  // Ensure CSRF token is sent
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Remove the row from the table
                const row = document.querySelector(`tr[data-absence-id='${absenceId}']`);
                if (row) {
                    row.remove();  // Remove the row from the DOM
                }
            } else {
                alert("削除に失敗しました。");
            }
        })        .catch(error => {
            console.error('Error:', error);
            alert("エラーが発生しました。もう一度お試しください。");
        });
    }
</script>

{% endblock %}

hkabtrak/absences/templates/new_absence.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit, maximum-scale=1">
    <title>Submit an Absence</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
          crossorigin="anonymous">

    <style>
        #instructions-box {
            background-color: #ffdeb9;
            border: 2px solid orange;
            color: black;
            padding: 10px;
            border-radius: 5px;
            margin-top: 10px;
            display: none;
        }

        #comment {
            border: 2px solid red;
        }
    </style>
</head>
<body>
<div class="container">
    <!-- Flash Messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="row mt-3">
                <div class="col-md-12">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    {% endwith %}

    <h1 class="text-center mt-5">Submit an Absence</h1>
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <form action="{{ url_for('absences.submit_absence') }}" method="post">

                <div class="mb-3">
                    <label for="parent_email" class="form-label">Parent's Email:</label>
                    <input type="email" class="form-control" id="parent_email" name="parent_email" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" title="Please enter a valid email address">
                </div>

                <div class="mb-3">
                    <label for="class_id" class="form-label">Class:</label>
                    <select class="form-select" id="class_id" name="class_id" required onchange="displayInstructions()">
                        <option value="">Select a Class</option>
                        {% for cls in classes %}
                            <option value="{{ cls.id }}"
                                    data-instructions="{{ cls.instructions }}">{{ cls.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="mb-3">
                    <label for="student_name" class="form-label">Student Name:</label>
                    <input type="text" class="form-control" id="student_name" name="student_name" required>
                </div>

                <div class="mb-3">
                    <label for="reason" class="form-label">Reason:</label>
                    <select class="form-select" id="reason" name="reason" required onchange="handleReasonChange()">
                        <option value="">Select a Reason</option>
                        <option value="Absent">Absent</option>
                        <option value="Late">Late</option>
                        <option value="Leaving Early">Leaving Early</option>
                        <option value="Absent for a Time">Absent for a Time</option>
                    </select>
                </div>


                <div class="row mb-3">
                    <div class="col-12 col-md-4">
                        <label for="date" class="form-label">Date:</label>
                        <input type="date" class="form-control" id="date" name="date" value="{{ today }}" min="{{ today }}" required>
                    </div>

                    <div class="col-12 col-md-4" id="start-time-section" style="display: none">
                        <label for="start_time" class="form-label">Start Time:</label>
                        <input type="time" class="form-control" id="start_time" name="start_time">
                    </div>

                    <div class="col-12 col-md-4" id="end-time-section" style="display: none">
                        <label for="end_time" class="form-label">End Time:</label>
                        <input type="time" class="form-control" id="end_time" name="end_time">
                    </div>
                </div>
                <div id="instructions-box"></div>

                <div class="mb-3">
                    <label for "comment" class="form-label">Comment:</label>
                    <textarea class="form-control" id="comment" name="comment" rows="4" required></textarea>
                </div>

                <button type="submit" class="btn btn-primary">Submit Absence</button>
            </form>
        </div>
    </div>
</div>

<!-- Optional JavaScript: jQuery, Popper.js, Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.12.7/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js"></script>

<script>
    function displayInstructions() {
        const classSelect = document.getElementById("class_id");
        const instructionsBox = document.getElementById("instructions-box");

        const selectedOption = classSelect.options[classSelect.selectedIndex];
        const instructions = selectedOption.getAttribute("data-instructions");

        if (instructions && instructions.toLowerCase() != "none") {
            instructionsBox.innerHTML = `<strong>Teacher's Instructions:</strong> <br/>${instructions}`;
            instructionsBox.style.display = "block";
        } else {
            instructionsBox.style.display = "none";
        }
    }

    function handleReasonChange() {
        const reasonSelect = document.getElementById("reason");
        const reason = reasonSelect.value;

        const startTimeSection = document.getElementById("start-time-section");
        const startTimeLabel = document.getElementById("start_time").previousElementSibling;
        const endTimeSection = document.getElementById("end-time-section");
        const endTimeLabel = document.getElementById("end_time").previousElementSibling;

        switch (reason) {
            case "Absent":
                startTimeSection.style.display = "none";
                endTimeSection.style.display = "none";
                break;
            case "Late":
                startTimeSection.style.display = "block";
                startTimeLabel.innerHTML = "Expected Time:";
                endTimeSection.style.display = "none";
                break;
            case "Leaving Early":
                startTimeSection.style.display = "none";
                endTimeSection.style.display = "block";
                endTimeLabel.innerHTML = "Leaving At:";
                break;
            case "Absent for a Time":
                startTimeSection.style.display = "block";
                endTimeSection.style.display = "block";
                startTimeLabel.innerHTML = "Leaving Time:";
                endTimeLabel.innerHTML = "Return Time:";
                break;
            default:
                startTimeSection.style.display = "none";
                endTimeSection.style.display = "none";
        }
    }
</script>
</body>
</html>

hkabtrak/absences/templates/single_student.html
{% extends "chrome.html" %}

{% block content %}
<div class="container mt-3">
    <h1>{{ student_name }}欠課概要</h1>
    <form action="{{ url_for('absences.student_absences', grade=grade, student_name=student_name) }}" method="get">
        <div class="form-group">
            <label for="semesterSelect">学期を選択する:</label>
            <select name="semester_id" id="semesterSelect" class="form-control" onchange="this.form.submit()">
                <option value="-1" {% if not selected_semester %}selected{% endif %}>全てを見る</option>
                {% for semester in semesters %}
                <option value="{{ semester.id }}" {% if selected_semester and selected_semester.id == semester.id %}selected{% endif %}>
                    {{ semester.name }} ({{ semester.start_date.strftime('%Y-%m-%d') }} - {{ semester.end_date.strftime('%Y-%m-%d') }})
                </option>
                {% endfor %}
            </select>
        </div>
    </form>

    <h5>欠席日数: {{ days_missed }}</h5>

    <table class="table">
        <thead>
            <tr>
                <th>日付</th>
                <th>欠課種類</th>
                <th>理由</th>
                <th>欠課時間</th>
                <th>宿題受け渡し方法</th>
            </tr>
        </thead>
        <tbody>
            {% for absence in absences %}
            <tr>
                <td>{{ absence.date.strftime('%Y-%m-%d') }}</td>
                <td>{{ absence.absence_type }}</td>
                <td>{{ absence.reason }}</td>
                <td class="duration" data-hours="{{ absence.duration }}"></td>
                <td>{{ absence.comment }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
function formatDuration(hours) {
    if (hours) {
        const totalMinutes = Math.floor(hours * 60);
        const hoursPart = Math.floor(totalMinutes / 60);
        const minutesPart = totalMinutes % 60;
        return `${hoursPart}h ${minutesPart}min`;
    }
    else return '0h 0min'
}

document.querySelectorAll('.duration').forEach(element => {
    const hours = parseFloat(element.dataset.hours);
    element.textContent = formatDuration(hours);
});
</script>
{% endblock %}